# Generated by Django 4.1.3 on 2022-11-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=40)),
                ('carga_horaria', models.CharField(max_length=5)),
                ('instituicao', models.CharField(max_length=30)),
                ('certificado', models.FileField(upload_to='')),
            ],
        ),
    ]
